authors = ["Rod Kay"]
description = "Provides an Ada package family covering pure and applied mathematics."
licenses = "ISC"
long-description = "\nContains:\n\n   - Pure\n      - Arithmetic (covers quantity)\n      - Algebra    (covers structure)\n      - Geometry   (covers space)\n      - Analysis   (covers change)\n\n   - Applied\n      - Statistics\n      - Computational\n\n"
maintainers = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]
name = "lace_math"
project-files = ["library/math.gpr"]
version = "0.1.0"

[[depends-on]]
lace_shared = "*"

[[pins]]

[pins.lace_shared]
path = "../../lace_shared"

[build-switches."*"]
Compile_Checks = "none"
