authors = ["Daniel King"]
description = "SHA-3 and related algorithms"
licenses = "BSD-3-Clause"
maintainers = ["Daniel King <damaki.gh@gmail.com>"]
maintainers-logins = ["damaki"]
name = "libkeccak"
tags = ["spark","cryptography","security","hash","sha3","keccak","gimli","ascon","shake","cshake","kmac","tuplehash","parallelhash","kangarootwelve"]
version = "3.0.0"
website = "https://github.com/damaki/libkeccak"

[gpr-externals]
LIBKECCAK_ARCH = ["generic","x86_64"]
LIBKECCAK_BUILD_MODE = ["debug","optimize"]
LIBKECCAK_COMPILE_CHECKS = ["enabled","disabled"]
LIBKECCAK_CONTRACTS = ["enabled","disabled"]
LIBKECCAK_LIBRARY_TYPE = ["relocatable","static","static-pic"]
LIBKECCAK_RUNTIME_CHECKS = ["enabled","disabled"]
LIBKECCAK_SIMD = ["none","SSE2","AVX2"]
LIBKECCAK_STYLE_CHECKS = ["enabled","disabled"]

[[depends-on]]

[[pins]]

[build-switches."*"]
Compile_Checks = "none"
