name = "find_and_replace_tool"
description = "Simple find and replace tool based on rejuvenation library"
version = "23.0.0"
authors = ["Pierre van de Laar"]
maintainers = ["Pierre van de Laar <pierre.van.de.laar@gmail.com>"]
maintainers-logins = ["pjljvandelaar"]
executables = ["find_and_replace_tool"]

[[depends-on]]
libadalang = "*"
rejuvenation = "^23.0.0"

[[pins]]

[pins.rejuvenation]
path = ".."

[pins.libadalang]
path = "../../libadalang"

[build-switches."*"]
Compile_Checks = "none"
