authors = [
"Martin Krischik <krischik@users.sourceforge.net>",
]
description = "Atari / SIO2PC tools for ATR-files"
executables = [
"atr_tools-main",
]
licenses = "GPL-3.0-or-later"
long-description = "This is a tool to analyse, create and convert ATR files.\n\nATR files are used by various Atari 8bit emulators and hardware add ons. Currently implemented\n\n# Print Header\n\n```sh\n>atr_tools-main --print-header test-DD-DS-80.atr \nFile name        : test-DD-DS-80.atr\nMagic            :      16#296#\nParagraphs       :        46056\nSector size      :          256\nFlags            :         2#1#\nBad Sectors      :            0\nUnused           :        16#0#\nSectors          :         2880\nBytes            :       736896\nBoot Sectors     : true        \n\nFloppy disk double density, double sided, 80 track\n```\n\n# Create Floppy image\n\n```sh\n>atr_tools-main --verbose --format-floppy --density=DD --side=SS --track=80 test-DD-SS-80.atr\nFile created     : test-DD-SS-80.atr\nSector size      :          256\nSector per track :           18\nTracks per side  :           80\nSides per disk   :            1\n```\n\nDevelopment versions available with:\n\n```sh\nalr index --add \"git+https://github.com/krischik/alire-index.git#develop\" --name krischik\n```\n\nSource code and testsuite available on [SourceForge](https://git.code.sf.net/p/tutorial-6502/git)\n"
maintainers = [
"Martin Krischik <krischik@users.sourceforge.net>",
]
maintainers-logins = [
"krischik",
]
name = "atari_atr_tools"
tags = [
"atari",
"tools",
"retrocomputing",
"ada2022",
]
version = "1.1.1"
website = "https://sourceforge.net/projects/tutorial-6502"
[build-switches]
[build-switches.development]
contracts = "Yes"
runtime_checks = "Overflow"
[build-switches.release]
contracts = "No"
runtime_checks = "Default"
[build-switches.validation]
contracts = "Yes"
runtime_checks = "Everything"
[[depends-on]]
adacl = ">=5.12.0"
gnat = ">=12 & <2000"

