authors = ["Rod Kay"]
description = "Contains a set of low level re-usable Ada components."
licenses = "ISC"
long-description = "\nContains:\n\n   - lace.Events    : Provides a 'subject/oberver' 'event/response' facility.\n   - lace.Any       : Provides an interface to allow heterogenous containers.\n   - lace.fast_Pool : Provides a generic which allows fast allocation/deallocation.\n   - lace.Text      : Provides a DSA friendly set of text operations.\n\n"
maintainers = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]
name = "lace"
project-files = ["library/lace.gpr"]
version = "0.1.0"

[[depends-on]]
lace_shared = "*"

[[pins]]

[pins.lace_shared]
path = "../lace_shared"

[build-switches."*"]
Compile_Checks = "none"
