authors = ["AdaCore"]
description = "Ada unit test framework"
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
name = "aunit"
project-files = ["lib/gnat/aunit.gpr"]
tags = ["unit","test","unit-test"]
version = "23.0.0"

[configuration]
auto_gpr_with = true
disabled = true
generate_ada = true
generate_c = true
generate_gpr = true
output_dir = "config"

[gpr-externals]
AUNIT_BUILD_MODE = ["Devel","Install"]
AUNIT_RUNTIME = ["full","zfp","zfp-cross","ravenscar","ravenscar-cert","cert"]

[build-switches."*"]
Compile_Checks = "none"
