authors = ["Simon Wright"]
description = "Eigenvalues, eigenvectors for non-symmetric, non-Hermitian matrices"
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]
name = "gnat_math_extensions"
project-files = ["gnat_math_extensions.gpr"]
tags = ["matrices","blas","lapack"]
version = "1.1.0"
website = "https://github.com/simonjwright/gnat_math_extensions"

[[depends-on]]
libblas = "*"
liblapack = "*"

[[pins]]

[build-switches."*"]
Compile_Checks = "none"
