description = "Dynamo Ada Generator"
name = "dynamo"
version = "1.4.0"
authors = ["Stephane.Carrez@gmail.com"]
licenses = "Apache-2.0"
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["dynamo_tool.gpr"]
tags = ["uml","generator","database"]
website = "https://gitlab.com/stcarrez/dynamo"
executables = ["dynamo"]
long-description = "\n[![Build Status](https://img.shields.io/jenkins/s/https/jenkins.vacs.fr/Bionic-Dynamo.svg)](https://jenkins.vacs.fr/job/Bionic-Dynamo/)\n[![Test Status](https://img.shields.io/jenkins/t/https/jenkins.vacs.fr/Bionic-Dynamo.svg)](https://jenkins.vacs.fr/job/Bionic-Dynamo/)\n[![codecov](https://codecov.io/gh/stcarrez/dynamo/branch/master/graph/badge.svg)](https://codecov.io/gh/stcarrez/dynamo)\n[![Download](https://img.shields.io/badge/download-1.3.0-brightgreen.svg)](https://download.vacs.fr/dynamo/dynamo-1.3.0.tar.gz)\n[![License](https://img.shields.io/badge/license-APACHE2-blue.svg)](LICENSE)\n![Commits](https://img.shields.io/github/commits-since/stcarrez/dynamo/1.3.0.svg)\n\nThis Ada05 application is a code generator used to generate\nan Ada Web Application or database mappings from hibernate-like\nXML description, YAML doctrine model or UML models.  It provides various commands for the\ngeneration of a web application which uses the Ada Web Application framework\n(https://github.com/stcarrez/ada-awa/).\n\n"

[available."case(os)"]
linux = true
windows = true
macos = true
"..." = false

[[depends-on]]
security = "*"
servletada = "*"
serverfaces = "*"
utilada = "*"
elada = "*"
utilada_xml = "*"
ado_mysql = "*"
ado_sqlite = "*"
ado_postgresql = "*"
ado_all = "*"
xmlada = "*"
libgpr = "*"

[gpr-externals]
DYNAMO_BUILD = ["distrib","debug","optimize","profile","coverage"]
UTIL_OS = ["win32","win64","linux32","linux64","macos64","netbsd32","netbsd64","freebsd32","freebsd64"]

[gpr-set-externals."case(os)".linux."case(word-size)".bits-32]
UTIL_OS = "linux32"

[gpr-set-externals."case(os)".linux."case(word-size)".bits-64]
UTIL_OS = "linux64"

[gpr-set-externals."case(os)".macos]
UTIL_OS = "macos64"

[gpr-set-externals."case(os)".windows."case(word-size)".bits-32]
UTIL_OS = "win32"

[gpr-set-externals."case(os)".windows."case(word-size)".bits-64]
UTIL_OS = "win64"

[configuration]
disabled = true

[[actions]]
type = "post-fetch"
command = ["sh","./alire-setup.sh"]

[environment.PATH]
prepend = "${CRATE_ROOT}/bin"

[environment.MANPATH]
prepend = "${CRATE_ROOT}/man"

[[pins]]

[pins.security]
path = "../ada-security"

[pins.servletada]
path = "../ada-servlet"

[pins.serverfaces]
path = "../ada-asf"

[pins.utilada]
path = "../ada-util"

[pins.elada]
path = "../ada-el"

[pins.utilada_xml]
path = "../ada-util/xml"

[pins.ado_mysql]
path = "../ada-ado/mysql"

[pins.ado_sqlite]
path = "../ada-ado/sqlite"

[pins.ado_postgresql]
path = "../ada-ado/postgresql"

[pins.ado_all]
path = "../ada-ado/all"

[pins.xmlada]
path = "../../xmlada"

[pins.libgpr]
path = "../../gprbuild"

[build-switches."*"]
Compile_Checks = "none"
