authors = ["AdaCore"]
description = "The XML/Ada toolkit"
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
name = "xmlada"
project-files = ["distrib/xmlada.gpr","dom/xmlada_dom.gpr","sax/xmlada_sax.gpr","input_sources/xmlada_input.gpr","schema/xmlada_schema.gpr","unicode/xmlada_unicode.gpr"]
version = "23.0.0"
website = "https://github.com/AdaCore/xmlada"

[configuration]
auto_gpr_with = true
disabled = true
generate_ada = true
generate_c = true
generate_gpr = true
output_dir = "config"

[gpr-externals]
LIBRARY_TYPE = ["static","relocatable","static-pic"]
XMLADA_BUILD_MODE = ["distrib","Debug","Production","profile","coverage","nochecks"]

[[actions]]
command = ["sh","configure"]
directory = "."
type = "post-fetch"

[[depends-on]]

[[pins]]

[build-switches."*"]
Compile_Checks = "none"
