name = "demo"
description = "Ansiada demo"
version = "0.1.0-dev"
executables = ["demo"]

[[depends-on]]
ansiada = "*"

[[pins]]

[pins.ansiada]
path = ".."

[build-switches."*"]
Compile_Checks = "none"
