description = "SQLite binding for Ada"
name = "matreshka_sql_sqlite3"
version = "22.0.0"
website = "https://forge.ada-ru.org/matreshka"
authors = ["Vadim Godunko"]
licenses = "BSD-3-Clause"
maintainers = ["Vadim Godunko <vgodunko@gmail.com>","Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko","reznikmm"]
project-files = ["../../../gnat/matreshka_sql_sqlite3.gpr"]
tags = ["sql","database","db","sqlite"]

[configuration]
disabled = true

[[depends-on]]
libsqlite3 = "any"
matreshka_league = "*"

[[pins]]

[pins.matreshka_league]
path = "../matreshka_league"

[build-switches."*"]
Compile_Checks = "none"
