name = "zipdcf"
description = "Tools that can (un)zip document container files, Zip-based archive files"
version = "2.0.3"
website = "https://github.com/onox/dcf-ada"
licenses = "MIT"
tags = ["zip","document","container","archive"]
executables = ["zipdcf","unzipdcf"]
authors = ["onox","Gautier de Montmollin"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[build-switches.validation]
compile_checks = "warnings"

[build-switches."*"]
style_checks = ["-gnatygAO-Is"]
Compile_Checks = "none"

[[depends-on]]
dcf = "^2.0"

[[pins]]

[pins.dcf]
path = "../dcf"
