authors = ["onox","Gautier de Montmollin"]
description = "Ada 2012 library for document container files, Zip-based archive files"
licenses = "MIT"
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]
name = "dcf"
tags = ["zip","document","container","archive"]
version = "2.0.3"
website = "https://github.com/onox/dcf-ada"
project-files = ["dcf/dcf.gpr"]

[build-switches."*"]
style_checks = ["-gnatygAO-Is"]
Compile_Checks = "none"

[build-switches.validation]
compile_checks = "warnings"
