authors = [
"Felix Krause",
]
description = "Text rendering library for OpenGLAda"
licenses = "MIT"
maintainers = [
"Felix Krause <contact@flyx.org>",
]
maintainers-logins = [
"flyx",
]
name = "openglada_text"
project-files = [
"opengl-text.gpr",
]
tags = [
"opengl",
"rendering",
"fonts",
]
version = "0.9.0"
website = "http://flyx.github.io/OpenGLAda/"
[[depends-on]]
freetypeada = "~0.1.0"
openglada = "~0.9.0"

