authors = ["AdaCore"]
description = "GNAT Project File Library"
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
name = "libgpr"
project-files = ["gpr/gpr.gpr"]
version = "23.0.0"

[configuration]
auto_gpr_with = true
disabled = true
generate_ada = true
generate_c = true
generate_gpr = true
output_dir = "config"

[gpr-externals]
GPR_BUILD = ["debug","production","coverage","profiling"]
LIBRARY_TYPE = ["static","relocatable","static-pic"]

[[depends-on]]
xmlada = "*"

[[pins]]

[pins.xmlada]
path = "../xmlada"

[build-switches."*"]
Compile_Checks = "none"
