authors = ["AdaCore"]
description = "A simple library to spawn processes and communicate with them."
licenses = "Apache-2.0"
long-description = "This is Glib integrated implementation of a spawn processes interface."
maintainers = ["Vadim Godunko <vgodunko@gmail.com>","Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko","reznikmm"]
name = "spawn_glib"
project-files = ["gnat/spawn_glib.gpr"]
tags = ["process","launch","pipe","glib"]
version = "23.0.0"
website = "https://github.com/AdaCore/spawn"

[configuration]
auto_gpr_with = true
disabled = true
generate_ada = true
generate_c = true
generate_gpr = true
output_dir = "config"

[gpr-externals]
OS = ["unix","osx","Windows_NT"]

[gpr-set-externals]
OS = "unix"

[[depends-on]]
gtkada = "*"

[[pins]]

[pins.gtkada]
path = "../../gtkada"

[build-switches."*"]
Compile_Checks = "none"
