description = "Ada Database Objects (SQLite)"
tags = ["database","uml","sql","sqlite"]
name = "ado_sqlite"
version = "2.3.0"
licenses = "Apache-2.0"
authors = ["Stephane.Carrez@gmail.com"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["../.alire/sqlite/ado_sqlite.gpr"]
website = "https://gitlab.com/stcarrez/ada-ado"
long-description = "\n[![Build Status](https://img.shields.io/jenkins/s/https/jenkins.vacs.fr/Ada-ADO.svg)](https://jenkins.vacs.fr/job/Ada-ADO/)\n[![Test Status](https://img.shields.io/jenkins/t/https/jenkins.vacs.fr/Ada-ADO.svg)](https://jenkins.vacs.fr/job/Ada-ADO/)\n[![codecov](https://codecov.io/gh/stcarrez/ada-ado/branch/master/graph/badge.svg)](https://codecov.io/gh/stcarrez/ada-ado)\n[![Documentation Status](https://readthedocs.org/projects/ada-ado/badge/?version=latest)](https://ada-ado.readthedocs.io/en/latest/?badge=latest)\n\nThis is the SQLite driver for the Ada Database Objects library.\n\n"

[[depends-on]]
ado = "*"
libsqlite3 = "any"

[gpr-externals]
ADO_LIBRARY_TYPE = ["relocatable","static","static-pic"]
BUILD = ["distrib","debug","optimize","profile","coverage"]

[configuration]
disabled = true

[[pins]]

[pins.ado]
path = ".."

[build-switches."*"]
Compile_Checks = "none"
