authors = [
"Alejandro R. Mosteo",
]
description = "Alex's Ada Assortment (of miscellaneous utilities)"
licenses = "LGPL-3.0-only"
long-description = "Alex's Ada Assortment of Utilities\n\n- Text formatting (paragraphs, tables).\n- Indefinite containers.\n- Enumeration validity/conversions of string images.\n- On-demand stack backtraces.\n- String containers and utilities.\n- Simple subprocess spawning.\n- Write-through minimal cache for objects stored in files\n"
maintainers = [
"alejandro@mosteo.com",
]
maintainers-logins = [
"mosteo",
]
name = "aaa"
tags = [
"miscellanea",
"utility",
]
version = "0.2.6"
website = "https://github.com/mosteo/aaa"

