name = "examples"
description = "Examples to use the rejuvenation library"
version = "22.0.0"
authors = ["Pierre van de Laar"]
maintainers = ["Pierre van de Laar <pierre.van.de.laar@gmail.com>"]
maintainers-logins = ["pjljvandelaar"]
executables = ["examples_main"]

[[depends-on]]
libadalang = "*"
rejuvenation = "^23.0.0"

[[pins]]

[pins.rejuvenation]
path = ".."

[pins.libadalang]
path = "../../libadalang"

[build-switches."*"]
Compile_Checks = "none"
