authors = ["Alejandro R. Mosteo"]
description = "Experimental implementation of ReactiveX in Ada"
licenses = "LGPL-3.0-only"
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
name = "rxada"
tags = ["rx","reactive","reactivex","observer"]
version = "0.1.1"
website = "https://github.com/mosteo/rxada"

[configuration]
auto_gpr_with = true
disabled = true
generate_ada = true
generate_c = true
generate_gpr = true
output_dir = "config"

[build-switches."*"]
Compile_Checks = "none"
