description = "Security Library for HTTP client and server with OAuth2 support"
name = "security"
version = "1.4.1"
licenses = "Apache-2.0"
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
authors = ["Stephane.Carrez@gmail.com"]
project-files = [".alire/security.gpr"]
tags = ["security","oauth2","authentication","permissions","jwt"]
website = "https://gitlab.com/stcarrez/ada-security"
long-description = "\n[![Build Status](https://img.shields.io/jenkins/s/http/jenkins.vacs.fr/Ada-Security.svg)](https://jenkins.vacs.fr/job/Ada-Security/)\n[![Test Status](https://img.shields.io/jenkins/t/http/jenkins.vacs.fr/Ada-Security.svg)](https://jenkins.vacs.fr/job/Ada-Security/)\n[![codecov](https://codecov.io/gh/stcarrez/ada-security/branch/master/graph/badge.svg)](https://codecov.io/gh/stcarrez/ada-security)\n[![Documentation Status](https://readthedocs.org/projects/ada-security/badge/?version=latest)](https://ada-security.readthedocs.io/en/latest/?badge=latest)\n\nAda Security provides a security framework which allows applications to define\nand enforce security policies. This framework allows users to authenticate by using\n[OpenID Authentication 2.0](https://openid.net/specs/openid-authentication-2_0.html)\nas well as [OAuth 2.0](https://oauth.net/2/) protocol.\nIt allows a web application to integrate easily with Yahoo!, Gitlab, Github, Facebook and\nGoogle+ authentication systems.\nThe Ada05 library includes:\n\n* An OpenID client authentication,\n* An OAuth 2.0 client authentication,\n* An OpenID Connect authentication framework,\n* An OAuth 2.0 server authentication framework,\n* A policy based security framework to protect the resources\n\n\n![Ada Security Overview](https://gitlab.com/stcarrez/ada-security/wiki/images/AdaSecurity.jpg)\n\nThe Ada Security library is used by the\n[Ada Web Application](https://gitlab.com/stcarrez/ada-awa)\nto provide authentication and access control to users within the web applications.\n\n"

[[depends-on]]
utilada = "*"
utilada_xml = "*"

[gpr-externals]
BUILD = ["distrib","debug","optimize","profile","coverage"]
SECURITY_LIBRARY_TYPE = ["relocatable","static","static-pic"]

[configuration]
disabled = true

[[pins]]

[pins.utilada]
path = "../ada-util"

[pins.utilada_xml]
path = "../ada-util/xml"

[build-switches."*"]
Compile_Checks = "none"
