authors = ["Alejandro R. Mosteo"]
description = "Semantic Versioning in Ada"
licenses = "LGPL-3.0-only"
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]
name = "semantic_versioning"
tags = ["semver","semantic","versioning"]
version = "2.1.0"
website = "https://github.com/alire-project/semantic_versioning"

[build-switches."*"]
Compile_Checks = "none"
