authors = ["Rod Kay"]
description = "A demo of GEL's human animation."
executables = ["launch_human_rig_demo"]
licenses = "ISC"
maintainers = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]
name = "lace_gel_animation_demo"
project-files = ["human_rig_demo.gpr"]
version = "0.1.0"

[[depends-on]]
lace_gel = "*"

[[pins]]

[pins.lace_gel]
path = "../lace/lace_gel"

[build-switches."*"]
Compile_Checks = "none"
