authors = ["Bent Bracke"]
description = "Library which contains various utility packages."
licenses = "CC0-1.0"
long-description = "Ada library which contains various utility packages. Currently only a few implementations of abstract data types."
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]
name = "brackelib"
tags = ["utility","adt","stack","queue"]
version = "0.0.2"
website = "https://github.com/bracke/brackelib"

[build-switches."*"]
Compile_Checks = "none"
