authors = [
"James Humphry",
]
description = "An Ada 2012 package to parse command line arguments and options"
licenses = "ISC"
maintainers = [
"James Humphry <alire@binecho.co.uk>",
]
maintainers-logins = [
"jhumphry",
]
name = "parse_args"
tags = [
"cli",
"command-line",
]
version = "0.9.0"
website = "https://github.com/jhumphry/parse_args"

