authors = [
"AdaCore",
]
description = "Platform agnostic drivers to interface external components"
licenses = "BSD-3-Clause"
long-description = "# embedded-components\n\nPlatform agnostic drivers to interface external components.\n\nThis crate is a snapshot of the `components` of [Ada Drivers\nLibrary](https://github.com/AdaCore/Ada_Drivers_Library/tree/master/components).\n\nAny bug report, issue, contribution must be adressed to the [Ada Drivers\nLibrary](https://github.com/AdaCore/Ada_Drivers_Library/) repo.\n\n"
maintainers = [
"chouteau@adacore.com",
]
maintainers-logins = [
"Fabien-Chouteau",
]
name = "embedded_components"
project-files = [
"embedded_components.gpr",
]
tags = [
"embedded",
"nostd",
]
version = "0.2.0"
website = "https://github.com/AdaCore/Ada_Drivers_Library/"
[build-switches]
[build-switches."*"]
style_checks = "no"
[[depends-on]]
adl_middleware = "~0.2.0"
hal = "~0.3.0"

