authors = [
"Rod Kay",
]
description = "Provides a thin Ada binding to the 'bullet' C++ project."
licenses = "ISC"
maintainers = [
"Rod Kay <rodakay5@gmail.com>",
]
maintainers-logins = [
"charlie5",
]
name = "lace_bullet"
project-files = [
"library/bullet_thin.gpr",
]
version = "0.1.0"
[[depends-on]]
lace_c_math = "~0.1"
libbullet = "*"

