authors = ["Martin Krischik <krischik@users.sourceforge.net>"]
description = "Ada Class Library"
licenses = "GPL-3.0-or-later"
long-description = "A class library for Ada for those who like OO programming.\n\nCurrently the following functionality is migrated to Ada 2022: \n\n* getopt commandline argument parser\n* string utilities\n* trace utility\n* reference counted smart pointer\n* AUnit compatible informative asserts\n\nDevelopment versions and testsuite available using the follwowing index:\n\n```sh\nalr index --add \"git+https://github.com/krischik/alire-index.git#develop\" --name krischik\n```\n\nSource code and testsuite available on [SourceForge](https://git.code.sf.net/p/adacl/git)\n"
maintainers = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers-logins = ["krischik"]
name = "adacl"
tags = ["library","command-line","trace","logging","string","aunit","assert","ada2022"]
version = "5.12.0"
website = "https://sourceforge.net/projects/adacl/"

[build-switches.development]
contracts = "Yes"
runtime_checks = "Overflow"

[build-switches.release]
contracts = "Yes"
runtime_checks = "Default"

[build-switches.validation]
contracts = "Yes"
runtime_checks = "Everything"

[build-switches."*"]
Compile_Checks = "none"

[[actions]]
command = ["alr","run"]
directory = "test"
type = "test"

[[depends-on]]

[[pins]]
