authors = ["Cyrill Korshnyak ł"]
description = "Simple library for simple logging. Like npm package \"debug\", but for Ada"
licenses = "Unlicense"
maintainers = ["Cyrill Korshnyak <kirillkorshnyak@yandex.com>"]
maintainers-logins = ["mangl-auf"]
name = "loga"
tags = ["logging"]
version = "1.0.0"
website = "https://github.com/mangl-auf/loga/"

[build-switches."*"]
Compile_Checks = "none"
