description = "Ada Database Objects (All drivers)"
tags = ["database","uml","sql","mysql","mariadb","sqlite","postgresql"]
name = "ado_all"
version = "2.3.0"
licenses = "Apache-2.0"
authors = ["Stephane.Carrez@gmail.com"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["../.alire/all/ado_all.gpr"]
website = "https://gitlab.com/stcarrez/ada-ado"
long-description = "\n[![Build Status](https://img.shields.io/jenkins/s/https/jenkins.vacs.fr/Ada-ADO.svg)](https://jenkins.vacs.fr/job/Ada-ADO/)\n[![Test Status](https://img.shields.io/jenkins/t/https/jenkins.vacs.fr/Ada-ADO.svg)](https://jenkins.vacs.fr/job/Ada-ADO/)\n[![codecov](https://codecov.io/gh/stcarrez/ada-ado/branch/master/graph/badge.svg)](https://codecov.io/gh/stcarrez/ada-ado)\n[![Documentation Status](https://readthedocs.org/projects/ada-ado/badge/?version=latest)](https://ada-ado.readthedocs.io/en/latest/?badge=latest)\n\nThis is the MySQL driver for the Ada Database Objects library.\n\n"

[[depends-on]]
ado_postgresql = "*"
ado_sqlite = "*"
ado_mysql = "*"

[gpr-externals]
ADO_LIBRARY_TYPE = ["relocatable","static","static-pic"]
BUILD = ["distrib","debug","optimize","profile","coverage"]

[configuration]
disabled = true

[[actions]]
type = "post-fetch"
command = ["gnatprep","-DHAVE_MYSQL=True","-DHAVE_SQLITE=True","-DHAVE_POSTGRESQL=True","../src/drivers/ado-drivers-initialize.gpb","../src/drivers/ado-drivers-initialize.adb"]

[[pins]]

[pins.ado_postgresql]
path = "../postgresql"

[pins.ado_sqlite]
path = "../sqlite"

[pins.ado_mysql]
path = "../mysql"

[build-switches."*"]
Compile_Checks = "none"
