authors = [
"Anton Fediushin",
]
description = "PBKDF2 implemented in Ada"
licenses = "ISC"
maintainers = [
"Anton Fediushin <imantonmeep@gmail.com>",
]
maintainers-logins = [
"AntonMeep",
]
name = "pbkdf2"
tags = [
"cryptography",
"security",
"pbkdf2",
]
version = "3.0.0"
website = "https://github.com/AntonMeep/pbkdf2"
[[depends-on]]
hmac = "^2.0.0"
sha1 = "^2.0.0"
sha2 = "^2.0.0"

