authors = ["AdaCore"]
description = "GNAT Project File Library"
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
name = "gpr_unit_provider"
version = "23.0.0"

[configuration]
auto_gpr_with = true
disabled = true
generate_ada = true
generate_c = true
generate_gpr = true
output_dir = "config"

[gpr-externals]
GPR_UNIT_PROVIDER_BUILD = ["debug","release","release_checks"]

[gpr-set-externals]
GPR_UNIT_PROVIDER_BUILD = "release"

[[depends-on]]
libadalang = "*"
libgpr2 = "*"

[[pins]]

[pins.libadalang]
path = "../libadalang"

[pins.libgpr2]
path = "../libgpr2"

[build-switches."*"]
Compile_Checks = "none"
