authors = [
"Fabien Chouteau",
]
description = "Library to encode and decode MIDI messages"
licenses = "MIT"
maintainers = [
"Fabien Chouteau <fabien.chouteau@gmail.com>",
]
maintainers-logins = [
"Fabien-Chouteau",
]
name = "midi"
tags = [
"midi",
"embedded",
"nostd",
]
version = "0.2.0"
website = "https://github.com/Fabien-Chouteau/MIDI"
[[depends-on]]
bbqueue = "~0.3.0"
gnat = ">=11"
hal = "~0.3.0"

