authors = [
"Alejandro R. Mosteo",
]
description = "A JSON-like data structure using Ada 2022 features"
licenses = "MIT"
maintainers = [
"Alejandro R. Mosteo <alejandro@mosteo.com>",
]
maintainers-logins = [
"mosteo",
]
name = "yeison"
tags = [
"json",
"yaml",
"toml",
"containers",
]
version = "0.1.0"
website = "https://github.com/mosteo/yeison"
[[depends-on]]
gnat = ">=11.2 & <2000"

