authors = [
"Gautier de Montmollin",
]
description = "HAC Ada Compiler: a small, quick Ada compiler covering a subset of Ada"
licenses = "MIT"
maintainers = [
"gdemont@hotmail.com",
]
maintainers-logins = [
"zertovitch",
]
name = "hac"
project-files = [
"hac.gpr",
]
tags = [
"hac",
"compiler",
]
version = "0.21.0"
website = "https://hacadacompiler.sourceforge.io/"
[gpr-externals]
HAC_Build_Mode = [
"Debug",
"Fast",
"Small",
]

