authors = [
"Rod Kay",
]
description = "Provides an openGL engine."
licenses = "ISC"
maintainers = [
"Rod Kay <rodakay5@gmail.com>",
]
maintainers-logins = [
"charlie5",
]
name = "lace_opengl"
project-files = [
"library/opengl.gpr",
]
version = "0.1.0"
[[depends-on]]
lace_collada = "~0.1"
libfreetype = "^2"

