authors = [
"Biser Milanov",
]
description = "SLIP Protocol Implementation"
licenses = "BSD-3-Clause"
maintainers = [
"bmilanov11@gmail.com",
]
maintainers-logins = [
"bmilanov",
]
name = "slip"
tags = [
"embedded",
"protocols",
"spark",
]
version = "0.0.1"
website = "https://gitlab.com/bmilanov/slip"

