description = "An Ada-binding the ØMQ library"
name = "zeromq_ada"
version = "4.1.5"
website = "https://github.com/persan/zeromq-Ada"
authors = ["Per Sandberg <per.s.sandberg@bahnhof.se>"]
licenses = "MIT AND GPL-2.0-only"
maintainers = ["Per Sandberg <per.s.sandberg@bahnhof.se>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["persan", "reznikmm"]
project-files = ["zmq.gpr"]
tags = ["network", "distributed", "messaging", "binding"]

[[actions]]
type = "post-fetch"
command = ["cp", "libzmq.gpr.in", "libzmq.gpr"]

[[actions]]
type = "post-fetch"
command = ["cp", "libsodium.gpr.in", "libsodium.gpr"]

[[depends-on]]
libzmq = "any"

[gpr-externals]
LIBRARY_TYPE = ["static", "relocatable"]
