authors = [
"AJ Ianozi",
]
description = "ISO Standard references for Ada such as 1366 & 4217 (Country & Currency)"
licenses = "MIT"
maintainers = [
"AJ Ianozi <aj@ianozi.com>",
]
maintainers-logins = [
"AJ-Ianozi",
]
name = "iso"
tags = [
"countries",
"currencies",
"iso-1366",
"iso-4217",
]
version = "2.0.0"
website = "https://github.com/ada-iso/ada_iso/"

