description = "Hardware Abstraction Layer (HAL)"
licenses = "BSD-3-Clause"
long-description = "# hal\n\nHardware Abstraction Layer: interfaces definitions to abstract access to common\nhardware devices and protocols\n\nThis crate is a snapshot of the `hal` in [Ada Drivers\nLibrary](https://github.com/AdaCore/Ada_Drivers_Library/tree/master/hal/src).\n\nAny bug report, issue, contribution must be adressed to the [Ada Drivers\nLibrary](https://github.com/AdaCore/Ada_Drivers_Library/) repo.\n\n"
maintainers = [
"chouteau@adacore.com",
]
maintainers-logins = [
"Fabien-Chouteau",
]
name = "hal"
project-files = [
"hal.gpr",
]
tags = [
"embedded",
"hal",
"nostd",
]
version = "0.3.0"

