authors = ["Alejandro R. Mosteo"]
description = "Simple task pool for parallelization"
licenses = "MIT OR Apache-2.0"
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
name = "workers"
tags = ["tasking","parallelization","pool"]
version = "0.1.0"
website = ""

[build-switches."*"]
Compile_Checks = "none"
