description = "Web Server Faces JSR 252, JSR 314 and JSR 344 (Testing framework)"
tags = ["web","servlet","http","framework","facelet","jsf","testing"]
name = "serverfaces_unit"
version = "1.5.0"
licenses = "Apache-2.0"
authors = ["Stephane.Carrez@gmail.com"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
website = "https://gitlab.com/stcarrez/ada-asf"
project-files = ["../.alire/unit/asf_unit.gpr"]
long-description = "\n[![Build Status](https://img.shields.io/jenkins/s/http/jenkins.vacs.fr/Ada-Server-Faces.svg)](https://jenkins.vacs.fr/job/Ada-Server-Faces/)\n[![Test Status](https://img.shields.io/jenkins/t/http/jenkins.vacs.fr/Ada-Server-Faces.svg)](https://jenkins.vacs.fr/job/Ada-Server-Faces/)\n[![codecov](https://codecov.io/gh/stcarrez/ada-asf/branch/master/graph/badge.svg)](https://codecov.io/gh/stcarrez/ada-asf)\n\nAda Server Faces allows to create web applications using the same pattern\nas the Java Server Faces (See JSR 252, JSR 314 and JSR 344). \n\nThis library provides a unit test framework that helps in building unit tests\non top of Ada Server Faces.\n\n"

[[depends-on]]
security = "*"
serverfaces = "*"
servletada = "*"
utilada = "*"
utilada_unit = "*"
servletada_unit = "*"

[gpr-externals]
BUILD = ["distrib","debug","optimize","profile","coverage"]
SECURITY_LIBRARY_TYPE = ["relocatable","static","static-pic"]

[configuration]
disabled = true

[[pins]]

[pins.security]
path = "../../ada-security"

[pins.serverfaces]
path = ".."

[pins.servletada]
path = "../../ada-servlet"

[pins.utilada]
path = "../../ada-util"

[pins.utilada_unit]
path = "../../ada-util/unit"

[pins.servletada_unit]
path = "../../ada-servlet/unit"

[build-switches."*"]
Compile_Checks = "none"
