authors = ["Alejandro R. Mosteo"]
description = "Optional values a la java.lang.Optional"
licenses = "LGPL-3.0-only"
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
name = "optional"
tags = ["optional","functional"]
version = "0.1.0"
website = "https://github.com/mosteo/optional/"

[build-switches."*"]
Compile_Checks = "none"
