authors = ["Alejandro R. Mosteo","Fabien Chouteau"]
description = "Command Line Interface Components"
licenses = "MIT AND GPL-3.0-or-later WITH GCC-exception-3.1"
long-description = "Command Line Interface Components:\n - \"git like\" subcommand handling\n - TTY color and formatting\n - User input queries\n - User configuration\n"
maintainers = ["alejandro@mosteo.com","Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["mosteo","Fabien-Chouteau"]
name = "clic"
tags = ["cli","command-line","user-input","tty"]
version = "0.2.1"
website = "https://github.com/alire-project/clic"

[[depends-on]]
aaa = "*"
ada_toml = "*"
ansiada = "*"
simple_logging = "*"

[[pins]]

[pins.aaa]
path = "../aaa"

[pins.ada_toml]
path = "../ada_toml"

[pins.ansiada]
path = "../ansiada"

[pins.simple_logging]
path = "../simple_logging"

[build-switches."*"]
Compile_Checks = "none"
