authors = [
"Fabien Chouteau",
]
description = "Generate GESTE data from Tiled maps and tilesets"
executables = [
"tiled_code_gen",
]
maintainers = [
"Fabien Chouteau <fabien.chouteau@gmail.com>",
]
maintainers-logins = [
"Fabien-Chouteau",
]
name = "tiled_code_gen"
tags = [
"geste",
"gamedev",
"game",
"tiled",
]
version = "0.1.0"
website = "https://github.com/Fabien-Chouteau/tiled-code-gen"
[[depends-on]]
apdf = "^5.0.0"
gnatcoll = "^21.0.0"
xmlada = "^21.0.0"

