authors = [
"Alejandro R. Mosteo",
]
description = "Wordle for the terminal"
executables = [
"wordle",
]
licenses = "MIT"
maintainers = [
"Alejandro R. Mosteo <alejandro@mosteo.com>",
]
maintainers-logins = [
"mosteo",
]
name = "wordle"
tags = [
"wordle",
"console",
"terminal",
"game",
]
version = "0.1.1"
[[depends-on]]
aaa = "~0.2.6"
ansiada = "^1.0.0"
wordlelib = "~0.1.0"
wordlist = "~0.1.2"

