authors = ["Felix Krause"]
description = "Image loading library for OpenGLAda"
licenses = "MIT"
maintainers = ["Felix Krause <contact@flyx.org>"]
maintainers-logins = ["flyx"]
name = "openglada_images"
project-files = ["opengl-images.gpr"]
tags = ["opengl","rendering","graphics"]
version = "0.9.0"
website = "http://flyx.github.io/OpenGLAda/"

[[depends-on]]
gid = "*"
openglada = "*"

[[pins]]

[pins.gid]
path = "../gid"

[pins.openglada]
path = "../openglada"

[build-switches."*"]
Compile_Checks = "none"
