authors = ["Stephen Leake"]
description = "Parser for Emacs ada-mode"
executables = ["ada_mode_wisi_lalr_parse","ada_mode_wisi_lr1_parse"]
licenses = "GPL-3.0-or-later"
maintainers = ["Stephen Leake <stephen_leake@stephe-leake.org>"]
maintainers-logins = ["stephe-ada-guru"]
name = "emacs_ada_mode"
project-files = ["emacs_ada_mode.gpr"]
tags = ["emacs","ada-mode"]
version = "8.0.5"
website = "https://www.nongnu.org/ada-mode/"

[[actions]]
command = ["make","-f","Alire.make","ada_annex_p_re2c.c"]
directory = "."
type = "pre-build"

[[depends-on]]
emacs_wisi = "*"
re2c = ">=2.0.3"
stephes_ada_library = "*"
wisitoken = "*"

[[pins]]

[pins.emacs_wisi]
path = "../emacs_wisi"

[pins.stephes_ada_library]
path = "../stephes_ada_library"

[pins.wisitoken]
path = "../wisitoken"

[build-switches."*"]
Compile_Checks = "none"
