authors = ["AdaCore"]
description = "GNAT Components Collection - Core packages"
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
name = "gnatcoll"
project-files = ["gnatcoll.gpr"]
tags = ["gnatcoll","json","email","refcount","projects","gpr","vfs"]
version = "23.0.0"
website = "https://github.com/adacore/gnatcoll-core"

[configuration]
auto_gpr_with = true
disabled = true
generate_ada = true
generate_c = true
generate_gpr = true
output_dir = "config"

[gpr-externals]
GNATCOLL_ATOMICS = ["intrinsic","mutex"]
GNATCOLL_BUILD_MODE = ["DEBUG","PROD"]
GNATCOLL_OS = ["windows","unix","osx"]
LIBRARY_TYPE = ["static","relocatable","static-pic"]

[gpr-set-externals]
GNATCOLL_BUILD_MODE = "PROD"
GNATCOLL_OS = "unix"
GNATCOLL_VERSION = "23.0.0"

[[depends-on]]
libgpr = "*"

[[pins]]

[pins.libgpr]
path = "../gprbuild"

[build-switches."*"]
Compile_Checks = "none"
