description = "Experimental YAML 1.3 implementation in Ada"
name = "adayaml"
version = "0.3.0"
website = "https://ada.yaml.io/"
authors = ["Felix Krause"]
executables = ["yaml-server"]
licenses = "MIT"
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]
project-files = ["yaml.gpr","yaml-utils.gpr","yaml-annotation_processor.gpr","yaml-server.gpr"]

[[depends-on]]
simple_components = "*"

[gpr-externals]
Mode = ["debug","release"]

[[pins]]

[pins.simple_components]
path = "../simple_components"

[build-switches."*"]
Compile_Checks = "none"
