authors = ["onox","David Blackman","Sebastiano Vigna"]
description = "xoshiro128++ and xoshiro256++ pseudo-random number generators"
licenses = "Apache-2.0"
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]
name = "xoshiro"
tags = ["xoshiro","rng","random","spark"]
version = "1.0.0"
website = "https://github.com/onox/xoshiro"

[configuration]
auto_gpr_with = true
disabled = true
generate_ada = true
generate_c = true
generate_gpr = true
output_dir = "config"

[build-switches."*"]
Compile_Checks = "none"
