authors = [
"Riccardo Bernardini",
]
description = "Native Ada library of special functions (e.g., beta, gamma)"
licenses = "MIT"
long-description = "This is a small native Ada library that provides few special functions like Beta, Gamma and Beta Incomplete. I wrote this because I needed those functions, therefore at the moment only the functions that I needed are present. This is a pure native Ada library and there is no dependence on external FORTRAN libraries."
maintainers = [
"Riccardo Bernardini <riccardo.bernardini@uniud.it>",
]
maintainers-logins = [
"fintatarta",
]
name = "specfun"
tags = [
"special-fun",
"numerics",
"beta-function",
"gamma-function",
"beta-incomplete",
]
version = "1.0.0"
website = "https://gitlab.com/my-ada-library/specfun"

