authors = ["Tama McGlinn"]
description = "Board Support package for Raspberry PI v1, v2 and B+"
licenses = "MIT"
maintainers = ["Tama McGlinn <t.mcglinn@gmail.com>"]
maintainers-logins = ["TamaMcGlinn"]
name = "raspberry_bsp"
tags = ["raspberry","pi"]
version = "1.0.0"
website = "https://github.com/TamaMcGlinn/ada_raspio"

[build-switches."*"]
Compile_Checks = "none"
