authors = [
"alejandro@mosteo.com",
]
description = "Ada wrapper for the fast Stachniss' Hungarian solver"
licenses = "LGPL-3.0-only"
maintainers = [
"alejandro@mosteo.com",
]
maintainers-logins = [
"mosteo",
]
name = "hungarian"
version = "1.0.0"
[gpr-externals]
Build_Type = [
"Debug",
"Release",
"No_Option",
"Profile",
]

