description = "Web Servlet Library following JSR 154, JSR 315 (AWS)"
tags = ["web","servlet","http","json"]
name = "servletada_aws"
version = "1.6.0"
licenses = "Apache-2.0"
authors = ["Stephane.Carrez@gmail.com"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["../.alire/aws/servletada_aws.gpr"]
website = "https://gitlab.com/stcarrez/ada-servlet"
long-description = "\n[![Build Status](https://img.shields.io/jenkins/s/http/jenkins.vacs.fr/Ada-Servlet.svg)](https://jenkins.vacs.fr/job/Ada-Servlet/)\n[![Test Status](https://img.shields.io/jenkins/t/http/jenkins.vacs.fr/Ada-Servlet.svg)](https://jenkins.vacs.fr/job/Ada-Servlet/)\n[![codecov](https://codecov.io/gh/stcarrez/ada-servlet/branch/master/graph/badge.svg)](https://codecov.io/gh/stcarrez/ada-servlet)\n\nAda Servlet allows to create web applications using the same pattern\nas the Java Servlet (See JSR 154, JSR 315). \n\nThis library integrates the Ada Servlet in the Ada Web Server.\n\n"

[[depends-on]]
servletada = "*"
utilada_aws = "*"

[gpr-externals]
BUILD = ["distrib","debug","optimize","profile","coverage"]
SERVLET_LIBRARY_TYPE = ["relocatable","static","static-pic"]

[configuration]
disabled = true

[[pins]]

[pins.servletada]
path = ".."

[pins.utilada_aws]
path = "../../ada-util/aws"

[build-switches."*"]
Compile_Checks = "none"
