authors = [
"Gautier de Montmollin",
]
description = "A collection of mathematical, 100% portable, packages"
executables = [
"arenstorf",
"arithmetic_compression",
"biomorph",
"champ_vt",
"cr_demo",
"fractal",
"gnat_int",
"ppm2func",
"show_floats_limits",
"test_beta",
"test_cholesky",
"test_copulas",
"test_ert",
"test_estimators",
"test_formulas",
"test_gamma",
"test_generic_real_linear_equations",
"test_normal",
"test_pareto",
"test_poisson",
"test_qr",
"test_random_performance",
"test_rsa",
"test_samples",
"test_sparse",
"test_u_rand",
"test_discrete_random_simulation",
]
licenses = "MIT"
maintainers = [
"alejandro@mosteo.com",
]
maintainers-logins = [
"mosteo",
"zertovitch",
]
name = "mathpaqs"
tags = [
"mathematics",
"numerics",
"algebra",
"matrix",
"probability",
"statistics",
"runge",
"kutta",
"runge-kutta",
]
version = "20230121.0.0"
website = "https://mathpaqs.sourceforge.io/"

