authors = [
"Alejandro R. Mosteo",
]
description = "Edit TOML files directly without parsing"
licenses = "MIT"
maintainers = [
"Alejandro R. Mosteo <alejandro@mosteo.com>",
]
maintainers-logins = [
"mosteo",
]
name = "toml_slicer"
tags = [
"toml",
]
version = "0.1.1"
website = "https://github.com/mosteo/toml_slicer"
[[depends-on]]
aaa = "~0.2.4|~0.3"

