authors = [
"Anton Fediushin",
]
description = "Convenience subprograms to convert between Big- and Little-endianness"
licenses = "ISC"
maintainers = [
"Anton Fediushin <imantonmeep@gmail.com>",
]
maintainers-logins = [
"AntonMeep",
]
name = "endianness"
tags = [
"spark",
"endianness",
"system",
]
version = "1.0.0"
website = "https://github.com/AntonMeep/endianness"

