authors = ["onox"]
description = "Use posix_spawn() to spawn processes without forking"
licenses = "Apache-2.0"
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]
name = "spoon"
tags = ["posix","spawn","process"]
version = "1.0.1"
website = "https://github.com/onox/spoon"

[build-switches."*"]
style_checks = ["-gnatygAO-Is"]
Compile_Checks = "none"

[build-switches.validation]
compile_checks = "warnings"
