authors = ["AdaCore"]
description = "GNAT Components Collection - postgres"
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
name = "gnatcoll_postgres"
project-files = ["gnatcoll_postgres.gpr"]
tags = ["gnatcoll","gnatcoll-db","postgres","postgresql","database"]
version = "23.0.0"
website = "https://github.com/adacore/gnatcoll-db"

[configuration]
auto_gpr_with = true
disabled = true
generate_ada = true
generate_c = true
generate_gpr = true
output_dir = "config"

[gpr-externals]
GNATCOLL_BUILD_MODE = ["DEBUG","PROD"]
LIBRARY_TYPE = ["static","relocatable","static-pic"]

[[depends-on]]
gnatcoll = "*"
gnatcoll_sql = "*"
postgresql = "*"

[[pins]]

[pins.gnatcoll]
path = "../../gnatcoll-core"

[pins.gnatcoll_sql]
path = "../sql"

[build-switches."*"]
Compile_Checks = "none"
