name = "check_pix16_swap"
description = ""
version = "0.1.0-dev"
executables = ["check_pix16_swap"]

[[depends-on]]
lvgl_ada = "*"

[[pins]]

[pins.lvgl_ada]
path = "../.."

[configuration.values.lvgl_ada]
Pixel_Bit_Depth = "Pix_16bit"
Color_16_Swap = true
Horizontal_Resolution = 800
Vertical_Resolution = 480
Density_Per_Inch = 100

[build-switches."*"]
Compile_Checks = "none"
