authors = [
"Lev Kujawski",
]
description = "SPARK83 implementation of the BLAKE2s hash function"
licenses = "MIT-0"
maintainers = [
"Lev Kujawski <int21h@mailbox.org>",
]
maintainers-logins = [
"lkujaw",
]
name = "blake2s"
tags = [
"ada1987",
"spark",
"hash",
"blake2",
"blake2s",
]
version = "0.1.3"
website = "https://github.com/lkujaw/blake2s"

