authors = [
"Stefan Hild",
]
description = "The Code of my 4X turn-based strategy game."
executables = [
"honki_tonks_zivilisationen",
]
licenses = "GPL-3.0-or-later"
long-description = "Der Code meines 4X-Rundenstrategiespiels. Geschrieben in Ada 2022 unter Verwendung der Ada Standardbibliothek, der ASFML 2.5.3, der CSFML 2.5.1 und der SFML 2.5.1. Nur unter Linux intensiv getestet, sollte aber auch unter anderen Betriebssystemen problemlos funktionieren.\n\nThe Code of my 4X turn-based strategy game. Written in Ada 2022 using the Ada standard library, the ASFML 2.5.3, the CSFML 2.5.1 and the SFML 2.5.1. Only intensively tested under Linux, but should also work without problems under other operating systems.\n"
maintainers = [
"Stefan Hild <krapfen@totalplanlos.de>",
]
maintainers-logins = [
"HonkiTonk",
]
name = "honki_tonks_zivilisationen"
tags = [
"game",
"sfml",
"4x",
"roundbased",
"strategy",
"cross-platform",
"multimedia",
"2d",
]
version = "0.5.510-dev"
website = "https://github.com/HonkiTonk/Honki-Tonks-Zivilisationen"
[[depends-on]]
asfml = "^2.5.3"
gnat = ">=12.0.0"

