authors = [
"onox",
]
description = "A library to replace names between colons with emojis"
licenses = "Apache-2.0"
maintainers = [
"onox <denkpadje@gmail.com>",
]
maintainers-logins = [
"onox",
]
name = "emojis"
tags = [
"emoji",
"string",
"text",
"unicode",
]
version = "1.0.1"
website = "https://github.com/onox/emojis"
[build-switches]
[build-switches."*"]
style_checks = [
"-gnatygAO-Is",
]
[build-switches.validation]
compile_checks = "warnings"

