authors = ["AdaCore"]
description = "Ada semantic analysis library extension and tools"
executables = ["gnatmetric","gnatpp","gnatstub","gnattest"]
licenses = "GPL-3.0-only WITH GCC-exception-3.1"
maintainers = ["Pierre-Marie de Rodat <pmderodat@kawie.fr>","Max Reznik <reznik@adacore.com>"]
maintainers-logins = ["pmderodat","reznikmm"]
name = "libadalang_tools"
project-files = ["src/lal_tools.gpr","src/build.gpr"]
tags = ["libadalang","static-analysis","metric","formatting","generator","gnatmetric","gnatpp","gnatstub","gnattest"]
version = "23.0.0"
website = "https://github.com/AdaCore/libadalang-tools"

[[actions]]
command = ["rm","-rf","valgrind"]
directory = "."
type = "post-fetch"

[[depends-on]]
libadalang = "*"
templates_parser = "*"

[[pins]]

[pins.libadalang]
path = "../libadalang"

[pins.templates_parser]
path = "../templates_parser"

[build-switches."*"]
Compile_Checks = "none"
