authors = ["Rod Kay"]
description = "Provides a thin Ada binding to the 'box2d' C++ project."
licenses = "ISC"
maintainers = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]
name = "lace_box2d"
project-files = ["library/box2d_thin.gpr"]
version = "0.1.0"

[[depends-on]]
lace_c_math = "*"

[[pins]]

[pins.lace_c_math]
path = "../lace_c_math"

[build-switches."*"]
Compile_Checks = "none"
