authors = ["onox"]
description = "Ada 2012 bindings for libcanberra"
licenses = "Apache-2.0"
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]
name = "canberra_ada"
tags = ["canberra","audio","sound","linux"]
version = "2.0.2"
website = "https://github.com/onox/canberra-ada"

[build-switches."*"]
style_checks = ["-gnatygAOM99-Is"]
Compile_Checks = "none"

[build-switches.validation]
compile_checks = "warnings"

[[depends-on]]
libcanberra = "~0.30.0"

[[pins]]
