authors = [
"Rod Kay",
]
description = "Provides 2D/3D rigid body dynamics simulation."
licenses = "ISC"
maintainers = [
"Rod Kay <rodakay5@gmail.com>",
]
maintainers-logins = [
"charlie5",
]
name = "lace_physics"
project-files = [
"library/physics.gpr",
]
version = "0.1.0"
[[depends-on]]
lace = "~0.1"
lace_box2d = "~0.1"
lace_bullet = "~0.1"

