authors = ["Dmitry A. Kazakov"]
description = "Simple Components - A collection of support packages"
licenses = "GPL-2.0-only WITH GCC-exception-2.0"
maintainers = ["alejandro@mosteo.com","blady.net@orange.fr"]
maintainers-logins = ["mosteo","Blady-Com"]
name = "simple_components"
project-files = ["components.gpr","components-connections_server.gpr","components-connections_server-elv_max_cube.gpr","components-connections_server-http_server.gpr","components-connections_server-http_server-sqlite_browser.gpr","components-connections_server-modbus.gpr","components-connections_server-mqtt.gpr","components-connections_server-secure.gpr","components-connections_server-smtp.gpr","components-gnutls.gpr","components-ntp.gpr","components-sqlite.gpr","strings_edit.gpr","tables.gpr"]
version = "4.62.0"
website = "http://www.dmitry-kazakov.de/ada/components.htm"

[gpr-externals]
Atomic_Access = ["Pragma-atomic","GCC-built-ins","GCC-long-offsets"]
Development = ["Debug","Release"]
Legacy = ["Ada95","Ada2005","Ada2012"]
Tasking = ["Multiple","Single"]
Traced_Objects = ["Off","On"]

[[depends-on]]
libgnutls = "^3.5.8"

[[pins]]

[build-switches."*"]
Compile_Checks = "none"
